
package(
    default_visibility = ["//visibility:public"],
)

licenses(["notice"])  # Apache 2.0

cc_library(
    name = "gvr",
    hdrs = [
        "mathfu_gvr_conversions.h",
    ],
    deps = [
        "@mathfu//:mathfu",
        "@gvr//:gvr",
    ],
)
