package(default_applicable_licenses = ["//third_party/lullaby:license"])

licenses(["notice"])

# Visibility group that specifies which projects can use the redux libraries.
package_group(
    name = "visibility",
    packages = [
        
        
        "//redux/...",
    ],
)
