
package(
    default_visibility = ["//visibility:public"],
)

licenses(["notice"])  # Apache 2.0

cc_library(
    name = "name",
    srcs = ["name_system.cc"],
    hdrs = ["name_system.h"],
    deps = [
        "//lullaby/generated",
        "//lullaby/modules/ecs",
        "//lullaby/systems/transform",
        "//lullaby/util:hash",
        "//lullaby/util:logging",
    ],
)
