# RenderEngine thunks implementations.

licenses(["notice"])

package(
    default_visibility = ["//redux:visibility"],
)

cc_library(
    name = "thunks",
    textual_hdrs = [
        "indirect_light.h",
        "light.h",
        "mesh.h",
        "render_engine.h",
        "render_layer.h",
        "render_scene.h",
        "render_target.h",
        "renderable.h",
        "texture.h",
    ],
    deps = [
        "//redux/engines/render",
    ],
)
