# PhysicsEngine thunks implementations.

licenses(["notice"])

package(
    default_visibility = ["//redux:visibility"],
)

cc_library(
    name = "thunks",
    textual_hdrs = [
        "physics_engine.h",
        "rigid_body.h",
        "trigger_volume.h",
    ],
    deps = [
        "//redux/engines/physics",
    ],
)
