# Stub implementations for optional components.

licenses(["notice"])

package(
    default_visibility = ["//redux:visibility"],
)

cc_library(
    name = "breaking",
    srcs = [
        "breaking.cc",
    ],
    deps = [
        "//redux/engines/text",
    ],
)
