# Audio Engine.

licenses(["notice"])

package(
    default_visibility = ["//redux:visibility"],
)

cc_library(
    name = "audio",
    srcs = [
    ],
    hdrs = [
        "audio_asset.h",
        "audio_engine.h",
        "sound.h",
        "sound_room.h",
    ],
    deps = [
        "//redux/modules/audio:enums",
        "//redux/modules/base:registry",
        "//redux/modules/base:resource_manager",
        "//redux/modules/base:typeid",
        "//redux/modules/math:quaternion",
        "//redux/modules/math:transform",
        "//redux/modules/math:vector",
    ],
)
