licenses(["notice"])  # Apache 2.0

cc_binary(
    name = "word_art_widths",
    srcs = [
        "word_art_widths.cc",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//:fbs",
        "//lullaby/util:arg_parser",
        "//lullaby/util:filename",
        "//lullaby/tools/common:file_utils",
    ],
)
